'use strict';
const fs = require('fs');
const path = require('path');
const REPO = 'D:\\code-project\\python\\PToEA';
const cm = fs.readFileSync(path.join(REPO, 'correctmanage.py'), 'utf8');
const m = cm.match(/_UI_HTML\s*=\s*r?"""([\s\S]*?)"""/);
let html = m[1];
console.log('script open tags in _UI_HTML:', (html.match(/<script/g) || []).length);
console.log('exact SCRIPT_TAG:', (html.match(/<script src="\/ui\/app\.js"><\/script>/g) || []).length);
const idx = html.indexOf('<script src="/ui/app.js"></script>');
console.log('script tag ctx:', JSON.stringify(html.slice(idx - 100, idx + 50)));
const appJs = fs.readFileSync(path.join(REPO, 'ui', 'app.js'), 'utf8');
console.log('appJs len:', appJs.length, '| has </script>:', appJs.indexOf('</script>'));
console.log('appJs occurrences of `script src`:', (appJs.match(/script src/g) || []).length);
const html2 = html.replace('<script src="/ui/app.js"></script>', function () { return '<script>' + appJs + '\nwindow.__X=1;</script>'; });
console.log('after replace — script open:', (html2.match(/<script/g) || []).length, 'close:', (html2.match(/<\/script>/g) || []).length);
const lines = html2.split('\n');
console.log('line1:', JSON.stringify(lines[1] && lines[1].slice(0, 90)));
for (let L = 2255; L <= 2262; L++) console.log('L' + L + ':', JSON.stringify(lines[L - 1] && lines[L - 1].slice(0, 110)));