const {JSDOM} = require('jsdom');
const dom=new JSDOM('<!doctype html><html><body><div id=page contenteditable=true></div></body></html>',{url:'http://127.0.0.1/'});
const window=dom.window;
const document=window.document;
const ed=document.getElementById('page');
ed.textContent='foo 123 foo 456 foo';
function parseRegexPattern(p){if(p.startsWith('/')){const m=p.match(new RegExp('^/(.*?)/([gimusy]*)$'));if(m)return{pattern:m[1],flags:m[2]};}return{pattern:p,flags:''}}
function _buildTextNodeList(root){var nodes=[];var offset=0;var walker=document.createTreeWalker(root,dom.window.NodeFilter.SHOW_TEXT,null,false);var node;while(node=walker.nextNode()){var len=node.textContent.length;nodes.push({node:node,start:offset,end:offset+len});offset+=len;}return nodes}
function _rangeFromOffsets(textNodes,startOff,endOff){if(startOff>=endOff||!textNodes.length)return null;var startNode=null,startIdx=0,endNode=null,endIdx=0;for(var i=0;i<textNodes.length;i++){var tn=textNodes[i];if(!startNode&&tn.end>startOff){startNode=tn.node;startIdx=startOff-tn.start;}if(tn.end>=endOff){endNode=tn.node;endIdx=endOff-tn.start;break;}}if(!startNode||!endNode)return null;const range=document.createRange();range.setStart(startNode,Math.min(startIdx,startNode.textContent.length));range.setEnd(endNode,Math.min(endIdx,endNode.textContent.length));return range}
function applySingleFormat(op,ed){const sel=window.getSelection();if(!sel.rangeCount)return;const r=sel.getRangeAt(0);const span=document.createElement('span');span.setAttribute('data-op',op);r.surroundContents(span);} 
function applyRegexMatchFormats(cond,ed){if(!cond||!cond.match_formats||!cond.match_formats.length)return; if(!cond.pattern)return;var rp=parseRegexPattern(cond.pattern);var flags=rp.flags.indexOf('g')>=0?rp.flags:rp.flags+'g';var re;try{re=new RegExp(rp.pattern,flags);}catch(e){console.error('bad regex',e);return}var text=ed.innerText||'';var textNodes=_buildTextNodeList(ed);var match;var mi=0;while((match=re.exec(text))!==null){if(!match[0]){re.lastIndex++;continue;}var fmts=cond.match_formats[mi]||[];mi++;if(!fmts.length||(fmts.length===1&&fmts[0]==='none'))continue;var matchStart=match.index;var matchEnd=matchStart+match[0].length;var range=_rangeFromOffsets(textNodes,matchStart,matchEnd);if(!range)continue;const sel=window.getSelection();sel.removeAllRanges();sel.addRange(range);for(var fi=0;fi<fmts.length;fi++){var op2=fmts[fi];if(op2==='none')continue;applySingleFormat(op2,ed);}}}
function applyRegexGroupFormats(cond,ed){if(!cond||!cond.group_formats||!cond.group_formats.length)return; if(!cond.pattern)return;var rp=parseRegexPattern(cond.pattern);var flags=rp.flags.indexOf('g')>=0?rp.flags:rp.flags+'g';var re;try{re=new RegExp(rp.pattern,flags);}catch(e){return}var text=ed.innerText||'';var textNodes=_buildTextNodeList(ed);var match;while((match=re.exec(text))!==null){if(!match[0]){re.lastIndex++;continue;}var offset=0;for(var gi=0;gi<cond.group_formats.length;gi++){var fmts=cond.group_formats[gi]||[];if(!fmts.length||(fmts.length===1&&fmts[0]==='none'))continue;var groupText=match[gi+1];if(!groupText)continue;var posInMatch=match[0].indexOf(groupText,offset);if(posInMatch<0)continue;var groupStart=match.index+posInMatch;var groupEnd=groupStart+groupText.length;offset=posInMatch+groupText.length;var range=_rangeFromOffsets(textNodes,groupStart,groupEnd);if(!range)continue;const sel=window.getSelection();sel.removeAllRanges();sel.addRange(range);for(var fi=0;fi<fmts.length;fi++){var op=fmts[fi];if(op==='none')continue;applySingleFormat(op,ed);}}}}
function evalFormatRule(rule,ed){const out=[];const groupConds=[];const matchConds=[];let page=false;for(const c of (rule&&rule.conditions)||[]){if(true){if(c.scope==='page')page=true;if(c.type==='regex'&&c.group_formats&&c.group_formats.length)groupConds.push(c);else if(c.type==='regex'&&c.match_formats&&c.match_formats.length)matchConds.push(c);else{const fmts=(c.formats||[]).filter(function(op){return op!=='none';});out.push.apply(out,fmts);}}}return {fmts:out,page:page,groupConds:groupConds,matchConds:matchConds};}
function applyFormatRule(rule,ed){const res=evalFormatRule(rule,ed);if(res.groupConds&&res.groupConds.length){for(var k=0;k<res.groupConds.length;k++){applyRegexGroupFormats(res.groupConds[k],ed);}}if(res.matchConds&&res.matchConds.length){for(var k2=0;k2<res.matchConds.length;k2++){applyRegexMatchFormats(res.matchConds[k2],ed);}}if(res.fmts&&res.fmts.length){const sel=window.getSelection();const r=document.createRange();r.selectNodeContents(ed);sel.removeAllRanges();sel.addRange(r);for(const op of res.fmts){applySingleFormat(op,ed);}}}

const rule={id:'r1',name:'r1',mode:'first',conditions:[{type:'regex',pattern:'foo\\s(\\d+)',scope:'selection',formats:[],match_formats:[['italic'],['align_center']]}]};
applyFormatRule(rule,ed);
console.log('html:',ed.innerHTML);
